### ISSUE TITLE
Projects Section

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/ewb-website#38]
- src/components/home/Projects.jsx
- user src/components/Title.jsx and src/components/home/Project.jsx
- feel free to change the with for the parent component in Project to make it look like the screenshot
- use the data in src/data/projects.js and map through it
```
PROJECTS.map((project, index)=><Project key = {index} name = {project.name} ...more props/>)
```
<img width="423" alt="image" src="https://github.com/acm-ucr/ewb-website/assets/73259022/7a919385-2ec7-462f-a92b-710102d7bbbc">

**Comment by sudhz** [comment]
Hi @menthy-wu, I would like to work on this issue under hacktoberfest. Could you please assign this to me?
